/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sporsalonu;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mert
 */
public class AnaGiris extends javax.swing.JFrame {

    /**
     * Creates new form AnaGiris
     */
    public void personelListesi() {
        String baslik[] = new String[]{"TC NO", "Adı", "Soyadı", "Telefon", "Eğitim Durumu", "Bölümü",};

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = null;
            Statement st = null;
            ResultSet rs = null;

            con = DriverManager.getConnection("jdbc:mysql://localhost/spor_salonu?useUnicode=true&characterEncoding=UTF-8", "root", "");
            st = con.createStatement();

            String sorgu21 = "select * from personel";
            rs = st.executeQuery(sorgu21);

            rs.last();
            int kayitsayisi = rs.getRow();
            rs.beforeFirst();

            Object data[][] = new Object[kayitsayisi][];
            int i = 0;

            while (rs.next()) {
                data[i] = new Object[]{
                    rs.getString("tc"),
                    rs.getString("ad"),
                    rs.getString("soyad"),
                    rs.getString("tel"),
                    rs.getString("egitim"),
                    rs.getString("bolum"),};
                i++;
            }

            tabloPersonel.setModel(new DefaultTableModel(data, baslik));

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Hata: " + ex.toString());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Veritabanına bağlantı sağlanamadı! " + ex.toString());
        }
    }

    public void uyelerListesi() {
        String baslik[] = new String[]{"TC NO", "Adı", "Soyadı", "Telefon", "Kayıt Tarihi", "Kayıt Süresi"};

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = null;
            Statement st = null;
            ResultSet rs = null;

            con = DriverManager.getConnection("jdbc:mysql://localhost/spor_salonu?useUnicode=true&characterEncoding=UTF-8", "root", "");
            st = con.createStatement();

            String sorgu21 = "select * from uyeler ";
            rs = st.executeQuery(sorgu21);

            rs.last();
            int kayitsayisi = rs.getRow();
            rs.beforeFirst();

            Object data[][] = new Object[kayitsayisi][];
            int i = 0;

            while (rs.next()) {
                data[i] = new Object[]{
                    rs.getString("tc"),
                    rs.getString("adi"),
                    rs.getString("soyadi"),
                    rs.getString("tel"),
                    rs.getString("kayitTarihi"),
                    rs.getString("kayitSuresi"),};
                i++;
            }

            tabloUyeler.setModel(new DefaultTableModel(data, baslik));

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Hata: " + ex.toString());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Veritabanına bağlantı sağlanamadı! " + ex.toString());
        }
    }

    public AnaGiris() {
        initComponents();
        uyelerListesi();
        personelListesi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        buttonCikis = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tAra = new javax.swing.JTextField();
        buttonUyeAra = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabloUyeler = new javax.swing.JTable();
        buttonUyeEkle = new javax.swing.JButton();
        buttonUyeSil = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        buttonCikis2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tPerAra = new javax.swing.JTextField();
        buttonPersonelAra = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabloPersonel = new javax.swing.JTable();
        buttonPersonelEkle = new javax.swing.JButton();
        buttonUyeSil2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ana Giriş");

        buttonCikis.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        buttonCikis.setText("ÇIKIŞ");
        buttonCikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCikisActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Üye Ara");

        tAra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tAraActionPerformed(evt);
            }
        });

        buttonUyeAra.setText("ÜYE ARA");
        buttonUyeAra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUyeAraActionPerformed(evt);
            }
        });

        tabloUyeler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabloUyeler);

        buttonUyeEkle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        buttonUyeEkle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/nav-save copy.png"))); // NOI18N
        buttonUyeEkle.setText("Yeni Üye Ekle");
        buttonUyeEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUyeEkleActionPerformed(evt);
            }
        });

        buttonUyeSil.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        buttonUyeSil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/Delete.jpg"))); // NOI18N
        buttonUyeSil.setText("Üye Sil");
        buttonUyeSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUyeSilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonCikis))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(tAra, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonUyeAra)))
                        .addGap(0, 41, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(buttonUyeEkle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonUyeSil, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonCikis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tAra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonUyeAra))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonUyeEkle)
                    .addComponent(buttonUyeSil))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Üyeler", jPanel1);

        buttonCikis2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        buttonCikis2.setText("ÇIKIŞ");
        buttonCikis2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCikis2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Personel Ara");

        buttonPersonelAra.setText("PERSONEL ARA");
        buttonPersonelAra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPersonelAraActionPerformed(evt);
            }
        });

        tabloPersonel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabloPersonel);

        buttonPersonelEkle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        buttonPersonelEkle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/nav-save copy.png"))); // NOI18N
        buttonPersonelEkle.setText("Personel Ekle");
        buttonPersonelEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPersonelEkleActionPerformed(evt);
            }
        });

        buttonUyeSil2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        buttonUyeSil2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/Delete.jpg"))); // NOI18N
        buttonUyeSil2.setText("Üye Sil");
        buttonUyeSil2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUyeSil2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(tPerAra, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonPersonelAra)))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonCikis2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(buttonUyeSil2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonPersonelEkle)
                .addGap(117, 117, 117))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonCikis2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tPerAra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonPersonelAra))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonPersonelEkle)
                    .addComponent(buttonUyeSil2))
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Çalışan Bilgileri", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPersonelEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPersonelEkleActionPerformed
        KullaniciEkle ac = new KullaniciEkle();
        ac.setVisible(true);
    }//GEN-LAST:event_buttonPersonelEkleActionPerformed

    private void buttonCikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCikisActionPerformed
        AnaGiris ac = new AnaGiris();
        ac.setVisible(false);
        dispose();
    }//GEN-LAST:event_buttonCikisActionPerformed

    private void buttonCikis2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCikis2ActionPerformed
        AnaGiris ac = new AnaGiris();
        ac.setVisible(false);
        dispose();
    }//GEN-LAST:event_buttonCikis2ActionPerformed

    private void buttonUyeEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUyeEkleActionPerformed
        UyeKaydi ac = new UyeKaydi();
        ac.setVisible(true);
    }//GEN-LAST:event_buttonUyeEkleActionPerformed

    private void tAraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tAraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tAraActionPerformed

    private void buttonUyeAraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUyeAraActionPerformed
        String uyeAra = tAra.getText();

        String baslik[] = new String[]{"TC NO", "Adı", "Soyadı", "Telefon", "Kayıt Tarihi", "Kayıt Süresi",};

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = null;
            Statement st = null;
            ResultSet rs = null;

            con = DriverManager.getConnection("jdbc:mysql://localhost/spor_salonu?useUnicode=true&characterEncoding=UTF-8", "root", "");
            st = con.createStatement();

            String sorgu21 = "select * from uyeler where adi like '%" + uyeAra + "%' or soyadi like '%" + uyeAra + "%' or tc like '%" + uyeAra + "%'";
            rs = st.executeQuery(sorgu21);

            rs.last();
            int kayitsayisi = rs.getRow();
            rs.beforeFirst();

            Object data[][] = new Object[kayitsayisi][];
            int i = 0;

            while (rs.next()) {

                data[i] = new Object[]{
                    rs.getString("tc"),
                    rs.getString("adi"),
                    rs.getString("soyadi"),
                    rs.getString("tel"),
                    rs.getString("kayitTarihi"),
                    rs.getString("kayitSuresi"),};
                i++;
            }

            tabloUyeler.setModel(new DefaultTableModel(data, baslik));

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Hata: " + ex.toString());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Veritabanına bağlantı sağlanamadı! " + ex.toString());
        }
    }//GEN-LAST:event_buttonUyeAraActionPerformed

    private void buttonUyeSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUyeSilActionPerformed
        int row = tabloUyeler.getSelectedRow();
        String secim_yap = tabloUyeler.getValueAt(row, 0).toString();

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = null;
            Statement st = null;
            ResultSet rs = null;

            con = DriverManager.getConnection("jdbc:mysql://localhost/spor_salonu?useUnicode=true&characterEncoding=UTF-8", "root", "");
            st = con.createStatement();

            String sorgu21 = "delete from uyeler where tc='" + secim_yap + "'";
            st.executeUpdate(sorgu21);

            JOptionPane.showMessageDialog(null, " " + " seçilen üye silinmiştir");

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Hata: " + ex.toString());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Veritabanına bağlantı sağlanamadı! " + ex.toString());
        }

        uyelerListesi();
    }//GEN-LAST:event_buttonUyeSilActionPerformed

    private void buttonPersonelAraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPersonelAraActionPerformed
        String personel_ara = tPerAra.getText();

        String baslik[] = new String[]{"TC NO", "Adı", "Soyadı", "Telefon", "Eğitim Durumu", "Bölümü",};

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = null;
            Statement st = null;
            ResultSet rs = null;

            con = DriverManager.getConnection("jdbc:mysql://localhost/spor_salonu?useUnicode=true&characterEncoding=UTF-8", "root", "");
            st = con.createStatement();

            String sorgu21 = "select * from personel where ad like '%" + personel_ara + "%' or soyad like '%" + personel_ara + "%' or tc like '%" + personel_ara + "%'";
            rs = st.executeQuery(sorgu21);

            rs.last();
            int kayitsayisi = rs.getRow();
            rs.beforeFirst();

            Object data[][] = new Object[kayitsayisi][];
            int i = 0;

            while (rs.next()) {

                data[i] = new Object[]{
                    rs.getString("tc"),
                    rs.getString("ad"),
                    rs.getString("soyad"),
                    rs.getString("tel"),
                    rs.getString("egitim"),
                    rs.getString("bolum"),};
                i++;
            }

            tabloPersonel.setModel(new DefaultTableModel(data, baslik));
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Hata: " + ex.toString());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Veritabanına bağlantı sağlanamadı! " + ex.toString());
        }
    }//GEN-LAST:event_buttonPersonelAraActionPerformed

    private void buttonUyeSil2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUyeSil2ActionPerformed
        int row = tabloPersonel.getSelectedRow();
        String secim_yap = tabloPersonel.getValueAt(row, 0).toString();

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = null;
            Statement st = null;
            ResultSet rs = null;

            con = DriverManager.getConnection("jdbc:mysql://localhost/spor_salonu?useUnicode=true&characterEncoding=UTF-8", "root", "");
            st = con.createStatement();

            String sorgu21 = "delete from personel where tc='" + secim_yap + "'";
            st.executeUpdate(sorgu21);

            JOptionPane.showMessageDialog(null, " seçilen personel silinmiştir");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Hata: " + ex.toString());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Veritabanına bağlantı sağlanamadı! " + ex.toString());
        }

        personelListesi();
    }//GEN-LAST:event_buttonUyeSil2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaGiris().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCikis;
    private javax.swing.JButton buttonCikis2;
    private javax.swing.JButton buttonPersonelAra;
    private javax.swing.JButton buttonPersonelEkle;
    private javax.swing.JButton buttonUyeAra;
    private javax.swing.JButton buttonUyeEkle;
    private javax.swing.JButton buttonUyeSil;
    private javax.swing.JButton buttonUyeSil2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField tAra;
    private javax.swing.JTextField tPerAra;
    private javax.swing.JTable tabloPersonel;
    private javax.swing.JTable tabloUyeler;
    // End of variables declaration//GEN-END:variables
}
